---
ID: "f82cb5f7-dd22-41a3-b745-e7a8b5b648dc"
Parent: "671c3f38-605e-494d-af99-aa8130df6f06"
Template: "671c3f38-605e-494d-af99-aa8130df6f06"
Path: /sitecore/templates/Feature/ACR/Navigation/Rendering Parameters/Side Navigation/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d04834e2-a4b4-4d3b-8eb6-3c5488a49953"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240605T143935Z
