---
ID: "5f292af0-5cf6-472f-86ed-f938cb820bfe"
Parent: "db1ca46d-29a8-4b1c-a9ab-49fe523c0853"
Template: "db1ca46d-29a8-4b1c-a9ab-49fe523c0853"
Path: /sitecore/templates/Foundation/ACR/Rendering Parameters/Base ACR Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240522T152954Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2368b60b-11e0-48ec-9b75-c6e06e12e052"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240522T152954Z
