---
ID: "02759908-0598-4f44-b801-f5c822518796"
Parent: "c65c472f-2b66-41cf-bf44-2b2674624389"
Template: "c65c472f-2b66-41cf-bf44-2b2674624389"
Path: /sitecore/templates/Foundation/ACR/Base Templates/_Image Base/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240506T210923Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kenneth.robinson@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kenneth.robinson@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8a3d1551-70aa-4156-9bfd-e47cf83762f0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kenneth.robinson@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240506T210923Z
