import { FacilitySearchProps } from './FacilitySearch.props';

export const defaultMockData: FacilitySearchProps = {
  params: {},
  rendering: {
    uid: '{00000000-0000-0000-0000-000000000000}',
    componentName: 'FacilitySearch',
    dataSource: '/',
  },
  fields: {
    searchOptions: [
      {
        id: 'ec9b0177-a4dd-4452-a724-d99644552be5',
        url: '/Data/Enumerations/Facility-Search/Search-Options/Zip?sc_site=ACR',
        name: 'Zip',
        displayName: 'Zip',
        fields: { Value: { value: 'Zip/City' } },
      },
      {
        id: '0c1f5493-ba73-447a-8df5-6775e71d4cc1',
        url: '/Data/Enumerations/Facility-Search/Search-Options/State?sc_site=ACR',
        name: 'State',
        displayName: 'State',
        fields: { Value: { value: 'State' } },
      },
      {
        id: '3d3416f0-7322-4cf3-ae11-b3921bd14c2f',
        url: '/Data/Enumerations/Facility-Search/Search-Options/Country?sc_site=ACR',
        name: 'Country',
        displayName: 'Country',
        fields: { Value: { value: 'Country' } },
      },
      {
        id: '29c187bb-e501-41ae-aa65-d3363cb5760a',
        url: '/Data/Enumerations/Facility-Search/Search-Options/Facility-Name?sc_site=ACR',
        name: 'Facility Name',
        displayName: 'Facility Name',
        fields: { Value: { value: 'Facility Name' } },
      },
    ],
    modalityOptions: [
      {
        id: '39edc55a-717b-4387-8c82-ed5d3ef0d407',
        url: '/Data/Enumerations/Facility-Search/Modality/Breast-MRI?sc_site=ACR',
        name: 'Breast MRI',
        displayName: 'Breast MRI',
        fields: { Value: { value: 'Breast MRI' } },
      },
      {
        id: '85571f6d-436b-4b39-8959-9a323dfc6ce9',
        url: '/Data/Enumerations/Facility-Search/Modality/Breast-Ultrasound?sc_site=ACR',
        name: 'Breast Ultrasound',
        displayName: 'Breast Ultrasound',
        fields: { Value: { value: 'Breast Ultrasound' } },
      },
      {
        id: '96972d44-95fe-4ef5-a1a3-4294dbcc36d0',
        url: '/Data/Enumerations/Facility-Search/Modality/Computed-Tomography?sc_site=ACR',
        name: 'Computed Tomography',
        displayName: 'Computed Tomography',
        fields: { Value: { value: 'Computed Tomography' } },
      },
      {
        id: 'e4a062f9-c901-461c-b19d-cc59b9b9cdb8',
        url: '/Data/Enumerations/Facility-Search/Modality/Mammography?sc_site=ACR',
        name: 'Mammography',
        displayName: 'Mammography',
        fields: { Value: { value: 'Mammography' } },
      },
      {
        id: '2a6fa8d7-82a2-44c1-b47b-27ef0b0044ac',
        url: '/Data/Enumerations/Facility-Search/Modality/MRI?sc_site=ACR',
        name: 'MRI',
        displayName: 'MRI',
        fields: { Value: { value: 'MRI' } },
      },
      {
        id: '07b43f0c-4b90-48ab-a953-a383aa10187e',
        url: '/Data/Enumerations/Facility-Search/Modality/Nuclear-Medicine?sc_site=ACR',
        name: 'Nuclear Medicine',
        displayName: 'Nuclear Medicine',
        fields: { Value: { value: 'Nuclear Medicine' } },
      },
      {
        id: 'c710e7da-8f7d-4030-bba3-34b45e77509b',
        url: '/Data/Enumerations/Facility-Search/Modality/PET?sc_site=ACR',
        name: 'PET',
        displayName: 'PET',
        fields: { Value: { value: 'PET' } },
      },
      {
        id: '6923dcc0-96da-47c1-b465-0f8fba9305d7',
        url: '/Data/Enumerations/Facility-Search/Modality/Radiation-Oncology?sc_site=ACR',
        name: 'Radiation Oncology',
        displayName: 'Radiation Oncology',
        fields: { Value: { value: 'Radiation Oncology' } },
      },
      {
        id: 'd9ba9e92-9b0b-4890-97f1-dbec5ef52834',
        url: '/Data/Enumerations/Facility-Search/Modality/Stereotactic?sc_site=ACR',
        name: 'Stereotactic',
        displayName: 'Stereotactic',
        fields: { Value: { value: 'Stereotactic' } },
      },
      {
        id: 'cd7ef8d3-7087-4803-a7f6-da7db12f323c',
        url: '/Data/Enumerations/Facility-Search/Modality/Ultrasound?sc_site=ACR',
        name: 'Ultrasound',
        displayName: 'Ultrasound',
        fields: { Value: { value: 'Ultrasound' } },
      },
    ],
    countryOptions: {
      id: '44af3939-5c25-4c9f-9aa8-e3095ff26107',
      url: '/Data/Enumerations/Countries/USA?sc_site=ACR',
      name: 'USA',
      displayName: 'USA',
      fields: { Value: { value: 'USA' } },
    },
    designationOptions: [
      {
        id: '9f65e791-9525-4f7f-be25-42fefdefe202',
        url: '/Data/Enumerations/Facility-Search/Designation/Comprehensive-Breast-Imaging-Center?sc_site=ACR',
        name: 'Comprehensive Breast Imaging Center',
        displayName: 'Comprehensive Breast Imaging Center',
        fields: {
          Value: { value: 'Comprehensive Breast Imaging Center (CBIC)' },
        },
      },
      {
        id: 'f012a82e-02b7-4384-a144-8511d4510826',
        url: '/Data/Enumerations/Facility-Search/Designation/Diagnostic-Imaging-Center-of-Excellence?sc_site=ACR',
        name: 'Diagnostic Imaging Center of Excellence',
        displayName: 'Diagnostic Imaging Center of Excellence',
        fields: {
          Value: { value: 'Diagnostic Imaging Center of Excellence (DICOE)' },
        },
      },
      {
        id: '697cd3c0-a7df-468b-adaf-08e09bf95fe1',
        url: '/Data/Enumerations/Facility-Search/Designation/Computed-Tomography---Pediatrics?sc_site=ACR',
        name: 'Computed Tomography - Pediatrics',
        displayName: 'Computed Tomography - Pediatrics',
        fields: { Value: { value: 'Computed Tomography - Pediatrics' } },
      },
      {
        id: 'daaa5f07-bb53-4391-8b25-3950296066d4',
        url: '/Data/Enumerations/Facility-Search/Designation/Lung-Cancer-Screening-Center?sc_site=ACR',
        name: 'Lung Cancer Screening Center',
        displayName: 'Lung Cancer Screening Center',
        fields: { Value: { value: 'Lung Cancer Screening Center' } },
      },
      {
        id: '1d6b7b94-a1f2-4007-9ef7-070cb0944787',
        url: '/Data/Enumerations/Facility-Search/Designation/Prostate-Cancer-MRI-Center?sc_site=ACR',
        name: 'Prostate Cancer MRI Center',
        displayName: 'Prostate Cancer MRI Center',
        fields: { Value: { value: 'Prostate Cancer MRI Center' } },
      },
    ],
    milesOptions: [
      {
        id: 'acf8fbc7-27af-4f23-9717-03ec7e845460',
        url: '/Data/Enumerations/Mile-Range/5-Miles?sc_site=ACR',
        name: '5 Miles',
        displayName: '5 Miles',
        fields: { Value: { value: '5' } },
      },
      {
        id: '643ccc5d-ca46-413d-ac61-2c126226e8b6',
        url: '/Data/Enumerations/Mile-Range/10-Miles?sc_site=ACR',
        name: '10 Miles',
        displayName: '10 Miles',
        fields: { Value: { value: '10' } },
      },
      {
        id: 'f734f6e0-6d4c-4e0b-a677-2581ab602ea1',
        url: '/Data/Enumerations/Mile-Range/25-Miles?sc_site=ACR',
        name: '25 Miles',
        displayName: '25 Miles',
        fields: { Value: { value: '25' } },
      },
      {
        id: '62d51407-4b9f-4684-a588-f87d73dcf337',
        url: '/Data/Enumerations/Mile-Range/50-Miles?sc_site=ACR',
        name: '50 Miles',
        displayName: '50 Miles',
        fields: { Value: { value: '50' } },
      },
    ],
    stateOptions: {
      id: '9e762ca7-3885-40f8-a1f4-0acd9f7b4024',
      url: '/Data/Enumerations/States/USA?sc_site=ACR',
      name: 'USA',
      displayName: 'USA',
      fields: {},
    },
  },
  externalFields: {
    searchOptions: [
      { name: 'Zip', value: 'Zip/City' },
      { name: 'State', value: 'State' },
      { name: 'Country', value: 'Country' },
      { name: 'Facility Name', value: 'Facility Name' },
    ],
    designationOptions: [
      { value: '00', name: 'N/A' },
      { value: 'BICOE', name: 'Comprehensive Breast Imaging Center (CBIC)' },
      { value: 'DICOE', name: 'Diagnostic Imaging Center of Excellence (DICOE)' },
      { value: 'ImageGently', name: 'Computed Tomography - Pediatrics' },
      { value: 'LCSC', name: 'Lung Cancer Screening Center' },
      { value: 'MRPC', name: 'Prostate Cancer MRI Center' },
    ],
    milesOptions: [
      { name: '5 Miles', value: '5' },
      { name: '10 Miles', value: '10' },
      { name: '25 Miles', value: '25' },
      { name: '50 Miles', value: '50' },
    ],
    modalityOptions: [
      { value: '00', name: 'N/A' },
      { value: 'BMRAP', name: 'Breast MRI' },
      { value: 'BUAP', name: 'Breast Ultrasound' },
      { value: 'CTAP', name: 'Computed Tomography' },
      { value: 'MAP', name: 'Mammography' },
      { value: 'MRAP', name: 'MRI' },
      { value: 'NMAP', name: 'Nuclear Medicine' },
      { value: 'PETAP', name: 'PET' },
      { value: 'RO', name: 'Radiation Oncology' },
      { value: 'SBBAP', name: 'Stereotactic' },
      { value: 'UAP', name: 'Ultrasound' },
    ],
    stateOptions: [
      { name: 'Wyoming', value: 'WY' },
      { name: 'Wisconsin', value: 'WI' },
      { name: 'West Virginia', value: 'WV' },
      { name: 'Washington', value: 'WA' },
      { name: 'Vermont', value: 'VT' },
      { name: 'Virginia', value: 'VA' },
      { name: 'Virgin Islands', value: 'VI' },
      { name: 'Utah', value: 'UT' },
      { name: 'Texas', value: 'TX' },
      { name: 'Tennessee', value: 'TN' },
      { name: 'South Dakota', value: 'SD' },
      { name: 'South Carolina', value: 'SC' },
      { name: 'Rhode Island', value: 'RI' },
      { name: 'Puerto Rico', value: 'PR' },
      { name: 'Pennsylvania', value: 'PA' },
      { name: 'Oregon', value: 'OR' },
      { name: 'Oklahoma', value: 'OK' },
      { name: 'Ohio', value: 'OH' },
      { name: 'Northern Mariana Islands', value: 'MP' },
      { name: 'North Dakota', value: 'ND' },
      { name: 'North Carolina', value: 'NC' },
      { name: 'New York', value: 'NY' },
      { name: 'New Mexico', value: 'NM' },
      { name: 'New Jersey', value: 'NJ' },
      { name: 'New Hampshire', value: 'NH' },
      { name: 'Nevada', value: 'NV' },
      { name: 'Nebraska', value: 'NE' },
      { name: 'Montana', value: 'MT' },
      { name: 'Missouri', value: 'MO' },
      { name: 'Mississippi', value: 'MS' },
      { name: 'Minnesota', value: 'MN' },
      { name: 'Michigan', value: 'MI' },
      { name: 'Massachusetts', value: 'MA' },
      { name: 'Maryland', value: 'MD' },
      { name: 'Maine', value: 'ME' },
      { name: 'Louisiana', value: 'LA' },
      { name: 'Kentucky', value: 'KY' },
      { name: 'Kansas', value: 'KS' },
      { name: 'Iowa', value: 'IA' },
      { name: 'Indiana', value: 'IN' },
      { name: 'Illinois', value: 'IL' },
      { name: 'Idaho', value: 'ID' },
      { name: 'Hawaii', value: 'HI' },
      { name: 'Guam', value: 'GU' },
      { name: 'Georgia', value: 'GA' },
      { name: 'Florida', value: 'FL' },
      { name: 'District of Columbia', value: 'DC' },
      { name: 'Delaware', value: 'DE' },
      { name: 'Connecticut', value: 'CT' },
      { name: 'Colorado', value: 'CO' },
      { name: 'California', value: 'CA' },
      { name: 'Arkansas', value: 'AR' },
      { name: 'Arizona', value: 'AZ' },
      { name: 'American Samoa', value: 'AS' },
      { name: 'Alaska', value: 'AK' },
      { name: 'Alabama', value: 'AL' },
    ],
    countryOptions: [
      { value: 'Bermuda', name: 'Bermuda' },
      { value: 'Brazil', name: 'Brazil' },
      { value: 'Canada', name: 'Canada' },
      { value: 'Chile', name: 'Chile' },
      { value: 'China', name: 'China' },
      { value: 'Colombia', name: 'Colombia' },
      { value: 'Cuba', name: 'Cuba' },
      { value: 'Egypt', name: 'Egypt' },
      { value: 'Germany', name: 'Germany' },
      { value: 'India', name: 'India' },
      { value: 'Italy', name: 'Italy' },
      { value: 'Japan', name: 'Japan' },
      { value: 'Kuwait', name: 'Kuwait' },
      { value: 'Lebanon', name: 'Lebanon' },
      { value: 'Marshall Islands', name: 'Marshall Islands' },
      { value: 'Palau', name: 'Palau' },
      { value: 'Panama', name: 'Panama' },
      { value: 'Philippines', name: 'Philippines' },
      { value: 'Poland', name: 'Poland' },
      { value: 'Qatar', name: 'Qatar' },
      { value: 'Saudi Arabia', name: 'Saudi Arabia' },
      { value: 'South Africa', name: 'South Africa' },
      { value: 'South Korea', name: 'South Korea' },
      { value: 'Spain', name: 'Spain' },
      { value: 'The Republic of Georgia', name: 'The Republic of Georgia' },
      { value: 'Turkey', name: 'Turkey' },
      { value: 'United Arab Emirates', name: 'United Arab Emirates' },
      { value: 'United Kingdom', name: 'United Kingdom' },
    ],
    seals: [
      {
        code: { value: 'BISCOE' },
        sealImage: {
          jsonValue: {
            value: {
              src: '',
              alt: 'Blackberry',
              width: '558',
              height: '952',
            },
          },
        },
      },
    ],
  },
};
