---
ID: "74789906-49b9-4f93-b109-68ebd8f84eb1"
Parent: "f40b79ea-4e98-49d6-bba1-2d50282ca1c1"
Template: "f40b79ea-4e98-49d6-bba1-2d50282ca1c1"
Path: /sitecore/templates/Feature/ACR/Global/Primary Navigation Column/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C3A09E59-D6B8-49BA-B281-ABEF65BAB82A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0c86fad1-884f-4167-afd2-11a8f99973b8"
      Hint: title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240603T173257Z
    - ID: "514f480a-41ba-4b35-8500-ef72a131993a"
      Hint: numberOfColumns
      Value: 1
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kenneth.robinson@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kenneth.robinson@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "57763753-2fda-4494-8937-b2ce9fde159d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kenneth.robinson@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240603T175624Z
