/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.


import { ComponentBuilder } from '@sitecore-jss/sitecore-jss-nextjs';

import { BYOCWrapper, FEaaSWrapper } from '@sitecore-jss/sitecore-jss-nextjs';

import * as Icon from 'src/components/ACR/Icon/Icon';
import * as DownloadIcon from 'src/components/ACR/Icon/svg/DownloadIcon';
import * as ExternalIcon from 'src/components/ACR/Icon/svg/ExternalIcon';
import * as RightArrowCircleIcon from 'src/components/ACR/Icon/svg/RightArrowCircleIcon';
import * as RightArrowIcon from 'src/components/ACR/Icon/svg/RightArrowIcon';
import * as LinkBase from 'src/components/ACR/Link/LinkBase';
import * as CdpPageView from 'src/components/SXA/CdpPageView';
import * as FEAASScripts from 'src/components/SXA/FEAASScripts';
import * as PartialDesignDynamicPlaceholder from 'src/components/SXA/PartialDesignDynamicPlaceholder';

export const components = new Map();
components.set('BYOCWrapper', BYOCWrapper);
components.set('FEaaSWrapper', FEaaSWrapper);

components.set('Icon', Icon);
components.set('DownloadIcon', DownloadIcon);
components.set('ExternalIcon', ExternalIcon);
components.set('RightArrowCircleIcon', RightArrowCircleIcon);
components.set('RightArrowIcon', RightArrowIcon);
components.set('LinkBase', LinkBase);
components.set('CdpPageView', CdpPageView);
components.set('FEAASScripts', FEAASScripts);
components.set('PartialDesignDynamicPlaceholder', PartialDesignDynamicPlaceholder);

export const componentBuilder = new ComponentBuilder({ components });

export const moduleFactory = componentBuilder.getModuleFactory();
