---
ID: "b6711ab1-35d7-4267-9555-c56a6217137c"
Parent: "aea4b379-1598-4f34-b816-925fe32d8bb8"
Template: "aea4b379-1598-4f34-b816-925fe32d8bb8"
Path: /sitecore/templates/Feature/ACR/Global/Rendering Parameters/Footer Link Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a6e199d3-bb19-4896-a881-b6e72bc2b4e3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240603T184045Z
