export enum IconName {
  CHEVRON_RIGHT = 'chevron-right',
  CHEVRON_DOWN = 'chevron-down',
  DOWNLOAD = 'download',
  EXTERNAL = 'external',
  RIGHT_ARROW = 'right-arrow',
  RIGHT_ARROW_CIRCLE = 'right-arrow-circle',
  LEFT_ARROW_CIRCLE = 'left-arrow-circle',
  BULLET = 'bullet',
  TWITTERX = 'twitterx',
  YOUTUBE = 'youtube',
  INSTAGRAM = 'instagram',
  FACEBOOK = 'facebook',
  LINKEDIN = 'linkedin',
}
