---
ID: "5afbdec8-b0b0-4ac9-8249-918e21e034bc"
Parent: "db553082-2cf4-4dda-becf-f84729780d34"
Template: "db553082-2cf4-4dda-becf-f84729780d34"
Path: /sitecore/templates/Feature/ACR/Global/Rendering Parameters/Social Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e8315071-3d40-4023-861c-9b0b93a1e48e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240603T200234Z
