---
ID: "5eb20fcf-1888-4560-8330-4e6fdb90f2e6"
Parent: "ac49b390-f119-49b9-a70e-f08c0f8e3a28"
Template: "ac49b390-f119-49b9-a70e-f08c0f8e3a28"
Path: /sitecore/templates/Feature/ACR/Global/Footer Link Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {CDE61F03-4175-4EC1-B0CC-192477155E79}
    {AC49B390-F119-49B9-A70E-F08C0F8E3A28}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240521T161110Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9a1ca172-aca2-4e8a-9b47-8e9df5b3e1f8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240521T161126Z
