---
ID: "a29dbaf8-ab5b-42e8-add8-5b442a5bb004"
Parent: "74ae2378-756b-4aa6-adec-df695b33f98a"
Template: "74ae2378-756b-4aa6-adec-df695b33f98a"
Path: /sitecore/templates/Project/ACR/Headless Site/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240501T180113Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\akhanal@acr.org
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\akhanal@acr.org
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f8c78d12-d000-4b96-9af9-ae6dbde0985e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\akhanal@acr.org
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240501T180113Z
