---
ID: "fdc220db-89f6-481e-80f9-baad898e24fe"
Parent: "b5c84aa4-ea73-4db3-91e8-7a7baded37bd"
Template: "b5c84aa4-ea73-4db3-91e8-7a7baded37bd"
Path: /sitecore/templates/Feature/ACR/Global/Rendering Parameters/Footer Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d84cf978-d51d-4028-ae60-99b0fd3c9f8b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240603T165515Z
