---
ID: "9a83a227-7d51-4dd7-bec5-7b4bcc6448fb"
Parent: "e5fd941f-4c8b-4ad5-8b7f-275feb830db6"
Template: "e5fd941f-4c8b-4ad5-8b7f-275feb830db6"
Path: /sitecore/templates/Feature/ACR/Multimedia/Multimedia Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F5CF0363-0DCB-461F-962F-21B46DD346E5}
    {E5FD941F-4C8B-4AD5-8B7F-275FEB830DB6}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240516T172212Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4bbc7582-2688-4433-a029-47701d06e05e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240516T172546Z
